#CircleCI Configuration File

version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install awscli==1.11.116
      - run:
          name: Build application Docker image
          command: |
            docker build -t app .
     

      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              CLUSTER='buildit'
              FAMILY='buildit'
              DOCKER_IMAGE='Buildit'
              TASK='buildit'
              SERVICE='buildit-task-Service-03T4HT2OZ4IMC'


              aws configure set region $AWS_REGION
              $(aws ecr get-login)

              
              docker tag app $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$DOCKER_IMAGE:$CIRCLE_SHA1
              docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$DOCKER_IMAGE:$CIRCLE_SHA1

              
              task_template='[
                {
                  "name": "%s",
                  "image": "%s.dkr.ecr.%s.amazonaws.com/%s:%s",
                  "essential": true,
                  "memoryReservation": 256,
                  "portMappings": [
                    {
                      "containerPort": 3000,
                      "hostPort": 80
                    }
                  ],
                  "environment" : [
                      { "name" : "Buildit", "value" : "env" }
                  ]
                }
              ]'
              echo "$task_template"
              task_def=$(printf "$task_template" $TASK $AWS_ACCOUNT_ID $AWS_REGION $TASK $CIRCLE_SHA1)

              
              json=$(aws ecs register-task-definition --container-definitions "$task_def" --family "$FAMILY")

              
              revision=$(echo "$json" | grep -o '"revision": [0-9]*' | grep -Eo '[0-9]+')

              
              aws ecs update-service --cluster "$CLUSTER" --service "$SERVICE" --task-definition "$TASK":"$revision"
              return 0
            fi
